config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_scope :customer do
    delete 'customers/guest_sign_out', to: 'public/sessions#guest_sign_out'
  end


  root to: "public/homes#top"
  get '/about', to: 'public/homes#about', as: 'about'

  get '/admin', to: 'admin/homes#top'

  get '/customers/my_page', to: 'public/customers#show'
  get '/customers/information/edit', to: 'public/customers#edit'
  patch '/customers/information', to: 'public/customers#update'
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :items, except: [:destroy]
  end

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  scope module: :public do
    resources :addresses, except: [:new, :show]
  end

  delete '/cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  post '/orders/confirm', to: 'public/orders#confirm'
  get '/orders/complete', to: 'public/orders#complete'

  scope module: :public do
    resources :orders, only: [:new, :create, :index, :show ]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com',
                       last_name: 'ゲスト',
                       first_name: 'ユーザ',
                       last_name_kana: 'ゲスト',
                       first_name_kana: 'ユーザ',
                       postal_code: '0000000',
                       address: '東京都渋谷区',
                       telephone_number: '09000000000',
                       is_deleted: false) do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end

  def customer_address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end

  def full_name
    self.last_name + " " + self.first_name
  end

  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end

  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
    
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,
    :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-md-4 text-center">
      <b class="mb-3"><%= @customer.full_name %>さんの会員情報編集</b>
    </div>
  </div>
  <div class="row md-8">
    <div class="col-md-8 offset-md-1">
      <table class="table">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
        <tr>
          <th>氏名</th>
          <td><label for="inputName" class="form-label"></label>
              <%= f.text_field :last_name, autofocus: true, id:"inputName", placeholder:"姓" %></td>
          <td><label for="inputFirstName" class="form-label"></label>
              <%= f.text_field :first_name, autofocus: true, id:"inputFirstName", placeholder:"名" %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><label for="inputNameKana" class="form-label"></label>
              <%= f.text_field :last_name_kana, autofocus: true, id:"inputNameKana", placeholder:"(セイ)" %></td>
          <td><label for="inputFirstNameKana" class="form-label"></label>
              <%= f.text_field :first_name_kana, autofocus: true, id:"inputFirstNameKana", placeholder:"名" %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><label for="inputPostalCode" class="form-label"></label>
              <%= f.text_field :postal_code, autofocus: true, id:"inputPostalCode", placeholder:"郵便番号" %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><label for="inputAddress" class="form-label"></label>
              <%= f.text_field :address, autofocus: true, id:"inputAddress", placeholder:"住所" %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><label for="inputTelephone" class="form-label"></label>
              <%= f.telephone_field :telephone_number, autofocus: true, id:"inputTelephone", placeholder:"電話番号" %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><label for="inputEmail" class="form-label"></label>
              <%= f.email_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス" %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td><%= f.radio_button :is_deleted, :false %>
          　　<%= f.label :is_deleted, "有効", value: :false %>
          　　<%= f.radio_button :is_deleted, :true %>
          　　<%= f.label :is_deleted, "退会", value: :true %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-5 text-center mr-2">
      <%= link_to "変更を保存", admin_customer_path(@customer.id), class: "btn btn-sm btn-success" %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 text-center">
      <h5 class="mb-3">会員一覧</h5>
    </div>
  </div>
  <div class="row">
     <div class="col-md-8 offset-md-1">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
              <td><%= customer.email %></td>
              <td><%= customer.customer_status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mb-5">
    <div class="col-md-4 text-center">
      <b class="mb-3"><%= @customer.full_name %>さんの会員詳細</b>
    </div>
  </div>
  <div class="row md-8">
    <div class="col-md-8 offset-md-1">
      <table class="table table-hover">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.full_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>ステータス</th>
          <td><%= @customer.customer_status %></td>
        </tr>
      </table>
    </div>
    <div class="col-md-5 text-center mr-2">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-sm btn-success" %>
      <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-sm btn-primary" %>
    </div>
  </div>
</div>