config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_scope :customer do
    delete 'customers/guest_sign_out', to: 'public/sessions#guest_sign_out'
  end


  root to: "public/homes#top"
  get '/about', to: 'public/homes#about', as: 'about'

  get '/admin', to: 'admin/homes#top'

  get '/customers/my_page', to: 'public/customers#show'
  get '/customers/information/edit', to: 'public/customers#edit'
  patch '/customers/information', to: 'public/customers#update'
  get '/customers/unsubscribe', to: 'public/customers#unsubscribe'
  patch '/customers/withdraw', to: 'public/customers#withdraw'

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :items, except: [:destroy]
  end

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  scope module: :public do
    resources :addresses, except: [:new, :show]
  end

  delete '/cart_items/destroy_all', to: 'public/cart_items#destroy_all'

  scope module: :public do
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  post '/orders/confirm', to: 'public/orders#confirm'
  get '/orders/complete', to: 'public/orders#complete'

  scope module: :public do
    resources :orders, only: [:new, :create, :index, :show ]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord


  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com',
                       last_name: 'ゲスト',
                       first_name: 'ユーザ',
                       last_name_kana: 'ゲスト',
                       first_name_kana: 'ユーザ',
                       postal_code: '0000000',
                       address: '東京都渋谷区',
                       telephone_number: '09000000000',
                       is_deleted: false) do |customer|
      customer.password = SecureRandom.urlsafe_base64
    end
  end

  def customer_address_display
    '〒' + postal_code + ' ' + address + ' ' + last_name + first_name
  end

  def full_name
    self.last_name + " " + self.first_name
  end

  def customer_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end

  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def get_image
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def sales_status
    if is_active == false
      "販売中止中"
    else
      "販売中"
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1}
  enum status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, sent: 4}

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    with_tax_price * amount
  end

  enum making_status: { impossible_manufacture: 0, wait_manufacture: 1, manufacturing: 2, finish: 3}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private

  def genre_params
    params.require(:genre).permit(:name)

  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.order('id DESC')
    @customers = Customer.all
    @order_detail = OrderDetail.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/56822bfd93.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body  class="d-flex flex-column vh-100">
    <header class="border-bottom">
      <nav class="navbar navbar-expand-lg navbar-light list-unstyled">
        <div class="container">
          <%= link_to "ながのCAKE", root_path, class: "btn btn-md rounded-pill" %>
          <% if customer_signed_in? %>
            <li>
              <%= link_to "マイページ", customers_my_page_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "カート", cart_items_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "ゲストログアウト", customers_guest_sign_out_path, method: :delete, class: "btn btn-light border" %>
            </li>
          <% elsif admin_signed_in? %>
            <li>
              <%= link_to "商品一覧", admin_items_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "会員一覧", admin_customers_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "注文履歴一覧", admin_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-light border" %>
            </li>
          <% else %>
            <li>
              <%= link_to "About", about_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "ログイン", new_customer_session_path, class: "btn btn-light border" %>
            </li>
            <li>
              <%= link_to "ゲストログイン", customers_guest_sign_in_path, method: :post,  class: "btn btn-light border" %>
            </li>
          <% end %>
        </div>
      </nav>
    </header>
    <main class="mb-auto mt-5">
    <%= yield %>
    </main>
    <footer class="border-top h-100">
      <div class="container">
        <div class="row">
          <div class="mx-auto">
             <p></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>